---
name: Build and Release on Mobile
on: [push, workflow_dispatch]
env:
  RUNNER_TOOL_CACHE: ${{ github.workspace }}/.toolcache
  RUNNER_TEMP: ${{ github.workspace }}/_temp
permissions:
    contents: write
jobs:
    build-mobile:
        runs-on: [self-hosted, macOS]
        strategy:
          matrix:
            targetPlatform:
                - iOS
        env:
            KEYCHAIN: job-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Install Python & Cocoapods via Homebrew
            run: |
                brew update
                arch -arm64 brew install python || true
                python3 --version 
                pip3 --version
                brew install cocoapods
            
          - name: Config SLRTK
            run: |
                pip3 install slrtk
                echo "Python libs installed"
                slrtk gtk install --unity --path .

          - uses: actions/cache@v3
            with:
                path: Library
                key: Library-iOS

            
          - uses: game-ci/unity-builder@v4
            env:
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
                UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
            with:
                targetPlatform: ${{ matrix.targetPlatform }}
                allowDirtyBuild: true

        #   - uses: actions/upload-artifact@v4
        #     with:
        #         name: Build
        #         path: build
        #     #don't really need to have entire build folder uploaded anymore since it works

          - name: Import Certs
            uses: apple-actions/import-codesign-certs@v3
            with:
                keychain: ${{ env.KEYCHAIN }}
                p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
                p12-password: ${{ secrets.P12_PASSWORD }}    

          - name: Install Provisioning Profile
            run: |
                # Create the directory if it doesn't exist
                mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
                # Decode the base64 secret and save it to the correct directory
                echo "${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Evan_Provisioning_Profile.mobileprovision

            # 5. Build the IPA with xcodebuild
          - name: Build Xcode project
            run: |
                PROJECT_PATH="build/iOS/iOS/Unity-iPhone.xcodeproj"
                SCHEME_NAME="Unity-iPhone"

                # Archive the project
                xcodebuild archive \
                    -project "$PROJECT_PATH" \
                    -scheme "$SCHEME_NAME" \
                    -archivePath "build/Unity-iPhone.xcarchive" \
                    -allowProvisioningUpdates \
                    CODE_SIGN_STYLE="Automatic" \

                # Export the .ipa
                xcodebuild -exportArchive \
                    -archivePath "build/Unity-iPhone.xcarchive" \
                    -exportPath "build/ipa" \
                    -exportOptionsPlist ${{ github.workspace }}/Assets/BuildPipeline/exportOptions.plist \
                    -allowProvisioningUpdates
            
          - uses: actions/upload-artifact@v4
            with:
                name: build-after-artifact
                path: build

            # 6. Upload the IPA as an artifact
          - name: Upload .ipa artifact
            uses: actions/upload-artifact@v4
            with:
                name: popsign-ipa
                path: build/ipa/*.ipa


        #cleanup
          - name: Delete keychain
            if: always()
            run: |
                security delete-keychain "${{ env.KEYCHAIN }}".keychain
    
...
