---
name: Build and Release on Mobile
on: [push, fork, workflow_dispatch]
permissions:
    contents: write
jobs:
    build-android:
        runs-on: [self-hosted, macOS]
        #TODO: Make step for actually building the app (1)
        #TODO: Make step for putting it on the android phone with ADB (3/4)
        #TODO:
        steps:
        #   i'm avoiding checking out the commit at all rn because i don't remember if i added those two dependencies to the repo
            
          - name: Build Android with Unity
            run: |
                /Applications/Unity/Hub/Editor/6000.0.26f1/Unity.app/Contents/MacOS/Unity \
                -batchmode \
                -quit \
                -projectPath "${{ github.workspace }}" \
                -executeMethod PopsignAIBuilder.BuildGameAndroid \
                -logFile build.log

          - name: Create Release
            uses: softprops/action-gh-release@v2
            with:
                files: |
                    Build/Android/*.apk
                tag_name: 1.0.0
                token: ${{ secrets.GITHUB_TOKEN }}
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
          - name: Deploy to Android Device
            run: | 
                echo "It's Honey-G"
            
...