---
name: Build and Release on Mobile
on: [push, workflow_dispatch]
env:
  RUNNER_TOOL_CACHE: ${{ github.workspace }}/.toolcache
  RUNNER_TEMP: ${{ github.workspace }}/_temp
permissions:
    contents: write
jobs:
    setup:
      runs-on: [self-hosted, macOS]
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Install Python & Cocoapods via Homebrew
            run: |
                brew update
                arch -arm64 brew install python || true
                python3 --version 
                pip3 --version
                brew install cocoapods
            
          - name: Config SLRTK
            run: |
                pip3 install slrtk
                echo "Python libs installed"
                slrtk gtk install --unity --path .

          # - name: Check for XCode Component Updates
          #   run: |
          #       sudo xcodebuild -license accept
          #       sudo xcodebuild -runFirstLaunch -checkForNewerComponents 
          #       sudo xcodebuild -downloadPlatform iOS
          #       # prevents no build target issue

    build-mobile:
        runs-on: [self-hosted, macOS]
        needs: [setup]
        strategy:
          matrix:
            targetPlatform:
                - iOS
                - Android
        steps:
          - uses: actions/cache@v3
            with:
                path: Library
                key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('**/Packages/manifest.json') }}
                restore-keys: |
                    Library-${{ matrix.targetPlatform }}-
                    Library-

          - name: Build with Unity Builder
            uses: game-ci/unity-builder@v4
            env:
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
                UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
            with:
                targetPlatform: ${{ matrix.targetPlatform }}
                allowDirtyBuild: true

          - name: Upload build folder artifact
            uses: actions/upload-artifact@v4
            with:
                name: build-folder-after-${{ matrix.targetPlatform }}
                path: build

    export-ios:
        needs: build-mobile
        runs-on: [self-hosted, macOS]
        env:
            KEYCHAIN: job-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
        steps:

          - name: Download build folder artifact
            uses: actions/download-artifact@v4
            with:
                name: build-folder-after-iOS
                path: build

          - name: Import Certs
            uses: apple-actions/import-codesign-certs@v3
            with:
                keychain: ${{ env.KEYCHAIN }}
                p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
                p12-password: ${{ secrets.P12_PASSWORD }}    

          - name: Install Provisioning Profile
            run: |
                # Create the directory if it doesn't exist
                mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
                # Decode the base64 secret and save it to the correct directory
                echo "${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/PopSignReleaseTestingProfile.mobileprovision
        
          - name: Create XCArchive
            run: |
                xcodebuild archive \
                  -project "${{ github.workspace }}/build/iOS/iOS/Unity-iPhone.xcodeproj" \
                  -archivePath "${{ github.workspace }}/build/Unity-iPhone.xcarchive" \
                  -scheme Unity-iPhone \
                  -destination 'generic/platform=iOS' \
                  PROVISIONING_PROFILE_SPECIFIER="${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}" \
                  CODE_SIGN_IDENTITY="${{ secrets.CODE_SIGN_IDENTITY }}"

          - name: Generate Plist
            run: |
                echo '<?xml version="1.0" encoding="UTF-8"?>
                <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
                <plist version="1.0">
                <dict>
                    <key>method</key>
                    <string>release-testing</string>
                    <key>signingStyle</key>
                    <string>manual</string>
                    <key>provisioningProfiles</key>
                    <dict>
                        <key>${{ secrets.APPLE_APP_ID }}</key>
                        <string>${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}</string>
                    </dict>
                    <key>teamID</key>
                    <string>${{ secrets.APPLE_TEAM_ID }}</string>
                </dict>
                </plist>' > ${{ github.workspace }}/exportOptions.plist
            

          - name: Export IPA from Archive
            run: |
                xcodebuild -exportArchive \
                  -project "${{ github.workspace }}/build/iOS/iOS/Unity-iPhone.xcodeproj" \
                  -exportArchive \
                  -exportOptionsPlist "${{ github.workspace }}/exportOptions.plist" \
                  -archivePath "${{ github.workspace }}/build/Unity-iPhone.xcarchive" \
                  -exportPath "${{ github.workspace }}/build/release.ipa" \
                  PROVISIONING_PROFILE_SPECIFIER="${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}" \
                  CODE_SIGN_IDENTITY="${{ secrets.CODE_SIGN_IDENTITY }}"

            # Upload the IPA as an artifact
          - name: Upload .ipa artifact
            uses: actions/upload-artifact@v4
            with:
                name: popsign-ipa
                path: build/release.ipa/PopSignAI.ipa

        # Cleanup
          - name: Delete keychain
            if: always()
            run: |
                security delete-keychain "${{ env.KEYCHAIN }}".keychain
    
    create-release:
        runs-on: [self-hosted, macOS]
        needs: [build-mobile, export-ios]
        steps:
            - name: Download iOS build
              uses: actions/download-artifact@v4
              with:
                name: popsign-ipa
                path: PopSignAI.ipa

            - name: Download Android Build
              uses: actions/download-artifact@v5
              with:
                name: build-folder-after-Android
                path: android-build

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      PopSignAI.ipa/PopSignAI.ipa
                      ${{ github.workspace }}/android-build/Android/Android.apk/PopSignAI.arm64-v8a.apk
                      ${{ github.workspace }}/android-build/Android/Android.apk/PopSignAI.armeabi-v7a.apk
                  tag_name: Mobile-Releases-${{ github.run_number }}-${{ github.triggering_actor }}
                  token: ${{ secrets.GITHUB_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...